<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory).artifacts\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildThisFileDirectory).artifacts\bin\$(MSBuildProjectName)\</BaseOutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="obj\**\*.cs" />
    <Compile Remove="bin\**\*.cs" />
    <Compile Remove=".verify\**\*.cs" />
    <Compile Remove="$(MSBuildThisFileDirectory).artifacts\**\*.cs" />
    <EmbeddedResource Remove="obj\**\*" />
    <EmbeddedResource Remove="bin\**\*" />
    <EmbeddedResource Remove=".verify\**\*" />
    <EmbeddedResource Remove="$(MSBuildThisFileDirectory).artifacts\**\*" />
    <None Remove="obj\**\*" />
    <None Remove="bin\**\*" />
    <None Remove=".verify\**\*" />
    <None Remove="$(MSBuildThisFileDirectory).artifacts\**\*" />
  </ItemGroup>
</Project>
